### ISSUE TITLE
Phase 2 - Relevance of first_pc

### ISSUE THREAD

**Issue by hekemp** [rpolley/CS2630-mips-asm#1]
I just wanted to note that while the code I put together for phase 2 works for the test case, I'm not very confident on it's accuracy because as far as I can tell there's no point in using the first_pc function. It's probably in our best interest to investigate this further to see what the purpose of first_pc is.

**Comment by rpolley** [comment]
i think the addresses are supposed to be relative to first_pc, basically it's the address of the first instruction we're given. your code really shouldn't pass the test, but looking at it it seems the test is wrong in the same way you were, as it expects -4 as the immediate which also ignores first_pc. i'll ask about it in class today
